cloudfoundry/cf-k8s-api

- Dockerfile
- Currently copies over `config.json` that will replaced with config mounted with k8s.
Co-authored-by: Akira Wong <wakira@vmware.com>
> Add Dockerfile for building cfapi image.

- apis/app_handler_test.go
- apis/route_handler_test.go
- go.mod
- go.sum
- main.go
- repositories/app_repository.go
- repositories/app_repository_test.go
- repositories/domain_repository.go
- repositories/domain_repository_test.go
- repositories/fixtures/vendir.lock.yml
- repositories/fixtures/vendor/cf-k8s-controllers/config/crd/bases/networking.cloudfoundry.org_cfdomains.yaml
- repositories/fixtures/vendor/cf-k8s-controllers/config/crd/bases/networking.cloudfoundry.org_cfroutes.yaml
- repositories/route_repository.go
- repositories/route_repository_test.go
- repositories/suite_test.go
Follow up to https://github.com/cloudfoundry/cf-k8s-controllers/issues/27
Co-authored-by: Ashwin Krishna <krishnaas@vmware.com>
Follow up to https://github.com/cloudfoundry/cf-k8s-controllers/issues/27
There is no new issue in this repo. Just an update chore.
Update the cf-k8s-controllers imports and reflect package organization changes in our code
No, changes should be purely cosmetic. Symbols for different api group imports now have distinct names.
`make` continues to successfully run
cc @akrishna90 and @gnovv as folks that will see merge conflicts as a result of the changes
> Update cf-k8s-controllers imports

- README.md
Relates to a couple issues that have touched the README recently.
- #1 
- #4 
Addresses some concerns that came up during acceptance. Primarily...
- Clarify dependency on cf-k8s-controllers
- Clarify usage of `vendir` by `envtest` tests
No
Follow the README and see if it makes sense 🙂
> DOC: Various README updates

- .github/workflows/test-build-push-pr.yml
Change workflow to tag images with PR number instead of branch name.
No.
> test-build-push-pr workflow update image tag

- config/rbac/role.yaml
- repositories/shared.go
#64 
This resolves an RBAC issue in the shim that prevented `Namespace` lookups.
No.
Deploy as normal, then run:
(Note: the namespace needs to be created first)
curl "<cluster-ip>/v3/apps" \
-H "Content-type: application/json" \
-d '{
"name": "my_app",
"relationships": {
"space": {
"data": {
"guid": "2f35885d-0c9d-4423-83ad-fd05066f8576"
}
}
}
}' 
@PureMunky
> Added RBAC for fetchign Namespaces

- apis/app_handler.go
- apis/fake/cfapp_repository.go
- apis/fake/cfdomain_repository.go
- apis/fake/cfroute_repository.go
- apis/route_handler.go
- apis/route_handler_test.go
- repositories/app_repository.go
- repositories/app_repository_test.go
- repositories/domain_repository.go
- repositories/domain_repository_test.go
- repositories/route_repository.go
- repositories/route_repository_test.go
No issue, just a verbally suggested team chore.
As title suggests, refactor interfaces that use context.Context to make it the first argument. For http serve consumers of those interfaces, pass request context to that argument.
No, the change is an in-place refactor.
Tests continue to pass, standard get requests on apps and routes continue to succeed.
pair @davewalter and cc suggester @matt-royal
> Refactor interfaces to take ctx as first arg

- apis/resource_matches_handler.go
- apis/resource_matches_handler_test.go
- docs/api.md
- main.go
- repositories/package_repository_test.go
- routes/routes.go
- routes/routes_test.go
#66 
Implemented naive Resource Matches endpoint for compatibility with CF CLI.
No.
* Run API against a Kubernetes cluster
* `curl -v "http://localhost:9000/v3/resource_matches" -X POST -H "Content-Type: application/json" -d '{}'`
@gnovv
> Implemented Resource Matching endpoint

- main.go
- routes/routes.go
- routes/routes_test.go
[#6](https://github.com/cloudfoundry/cf-k8s-api/issues/6)
Forgot to add routing code in https://github.com/cloudfoundry/cf-k8s-api/pull/76 . This will leave the server responding with 404s instead of actually routing the request to the handler that other wise works.
No
Same as #6.
cc @davewalter
> Add routing for list apps

- Dockerfile
- repositories/domain_repository.go
- repositories/domain_repository_test.go
#38
This PR fixes the implementation of FetchDomain to use `client.Get` instead of filtering a list, and to return the correct typed error when the domain is not found.
No
See #38 
@acosta11
> Fix implementation of FetchDomain

- Dockerfile
- apis/app_handler.go
- apis/fake/cfpackage_repository.go
- apis/package_handler.go
- apis/package_handler_test.go
- apis/route_handler.go
- payloads/app.go
- payloads/package.go
- payloads/route.go
- payloads/shared.go
- repositories/package_repository.go
- repositories/package_repository_test.go
No
Objects like the former repositories.CreatePackage are now "messages"
(e.g. repositories.PackageCreateMessage)
Also move payload.AppCreateMessageToAppRecord() to payload.AppCreate.ToRecord()
No
None (this is a pure chore)
@akrishna90
> Rename the message package and types to payload(s)

- config/rbac/role.yaml
- repositories/package_repository.go
#37 
Add rbac annotations so that the deployed version of the API can create CFPackage records
No
Follow the Acceptance Criteria on #37 
Paired with @acosta11
> Add missing RBAC annotation for CFPackages

- apis/app_handler.go
- apis/app_handler_test.go
#59 
This implements the workloads validation errors from `cf-k8s-controllers` in the app handler. Previously, it was a string compare.
No.
Run tests as normal.
@akrishna90 @davewalter
> Use workloads validation errors in app handler

- apis/app_handler.go
- apis/app_handler_test.go
- apis/package_handler.go
- apis/package_handler_test.go
- apis/resource_matches_handler.go
- apis/resource_matches_handler_test.go
- apis/root_handler.go
- apis/root_handler_test.go
- apis/root_v3_handler.go
- apis/root_v3_handler_test.go
- apis/route_handler.go
- apis/route_handler_test.go
- main.go
No
Introduce constructors for rest handlers. This is useful because:
* handlers fields can be private (basic OOP principle)
* Introducing a new field in the constructor would result into compilation errors wherever the constructor is invoked, therefore one will make sure to wire the handler dependencies properly
No
Not really, this is simple refactoring. However, run all tests, see them pass
@georgethebeatle
> Introduce contructors for rest handlers

- apis/root_handler.go
- apis/root_handler_test.go
- main.go
- presenter/root.go
https://github.com/cloudfoundry/cf-k8s-api/issues/10
Introduce a `cf_on_k8s` property into the `GET /` response which is always true in CF-on-K8S API. This property will be processed by the CLI to figure out that it is talking to CF-on-K8s rather than CF-on-VMs. See https://github.com/eirini-forks/cli/pull/1 for details.
The change is compatible with the CF-on-VMs CC API as the absence of that field defaults to `false` on the CLI side, i.e. CLI would know that it talks to CF-on-VMs without actually changing the CC API there. 
No
1. Start the API
2. `curl localhost:9000`
3. See `"cf_on_k8s": true` in the response body
@georgethebeatle
> Introduce `"cf_on_k8s": true` into the `/` response

- main.go
- repositories/build_repository.go
- repositories/build_repository_test.go
- repositories/package_repository_test.go
- repositories/suite_test.go
- Also fixed test flakiness with time constant
Co-authored-by: Ashwin Krishna <krishnaas@vmware.com>
No
As part of https://github.com/cloudfoundry/cf-k8s-controllers/issues/43 we removed the `"Ready"` Status Condition from the CFBuild Staging process. This PR adjusts the tests and the CFBuild repo to correctly derive the State field from the new Condition Status values.
no
Install K8s controllers via README, run api shim locally, create CFApp, CFPackage, CFBuild and confirm state returned by shim matches CFBuild.
@akrishna90
> Fix CFBuild Status Conditions

- repositories/app_repository.go
- repositories/app_repository_test.go
Issue #103 
Fix bug related to string trimming App GUIDs.
No.
Hard to reproduce bug since it it relies on GUID generation starting with an e.
@davewalter @mnitchev
> Fixed bug where leading e trimmed from App GUID

- Makefile
- README.md
- repositories/shared.go
No.
Source `controller-gen` and generate rbac via `manifests` make target
No.
Run `make manifests`. It should go get `controller-gen` and regenerate rbac.
@davewalter @acosta11
> Add controller-gen and manifests make targets

- apis/org_handler.go
- config/base/rbac/role.yaml
Make e2e tests green again.
This restores the permission accidentally removed from the service account role in https://github.com/cloudfoundry/cf-k8s-api/commit/8d0de889b
> Restore SubnamespaceAnchors list permission

- apis/app_handler.go
- apis/app_handler_test.go
- apis/build_handler_test.go
- apis/fake/cfapp_repository.go
- apis/package_handler_test.go
- apis/route_handler_test.go
- apis/shared_test.go
- docs/api.md
- main.go
- payloads/app.go
- presenter/app.go
- repositories/app_repository.go
- repositories/app_repository_test.go
#55 
It adds the PATCH `/v3/apps/:guid/current_droplet` endpoint and supporting code. It also introduces some test helpers for the UnprocessableEntity case
No
Follow the AC in the issue
@gnovv paired with me
> API Client can update currentDropletRef for an app via PATCH `/v3/apps/<app_guid>/relationships/current_droplet`

- config/base/rbac/role.yaml
- repositories/package_repository.go
https://github.com/cloudfoundry/cf-k8s-api/issues/46
Fixes the story rejection due to service account RBAC not being updated for uploading images.
No.
Same as https://github.com/cloudfoundry/cf-k8s-api/issues/46
@matt-royal
> Add Package RBAC for Service Accounts to upload source images

- Makefile
No.
Adding a make target for `docker-push` mirroring `cf-k8s-controllers` and standard kubebuilder projects.
No.
Run `make docker-push` after running `make docker-build`.
@PureMunky - should help with testing changes.
> Add phony make target for pushing docker images

- apis/apis_suite_test.go
- apis/fake/cfspace_repository.go
- apis/org_handler_test.go
- apis/space_handler.go
- apis/space_handler_test.go
- payloads/space.go
- presenter/org.go
- repositories/org_repository.go
- repositories/org_repository_test.go
- tests/e2e/spaces_test.go
https://github.com/cloudfoundry/cf-k8s-api/issues/61
Implement `POST /v3/spaces` so that API clients can create spaces
No
```
curl "https://api.example.org/v3/spaces" \
-X POST \
-H "Content-Type: application/json" \
-d '{
"name": "my-space",
"relationships": {     
"organization": {    
"data": {          
"guid": "<org-guid>"     
}                  
}                    
}'
```
* should succeed
* `curl https://api.example.org/v3/spaces` should list the space
@mnitchev @georgethebeatle
> Implement create spaces (POST /v3/spaces)
